hyperparameters:
    client:
        batch_size: 256
        local_epochs: 5
        loss: MultiMarginLoss
        target_epsilon: 100.0
        target_delta: 1.0e-07
        max_grad_norm: 1.0
        optimizer:
            lr: 0.001
            momentum: 0.9
            weight_decay: 0.001
        persistency: true
        scheduler:
            gamma: 1
            step_size: 1
    model: Medical_SVM
    net_args:
        input_dim: 26
    server:
        weighted: true
        lr: 1.0
        global_step: 1.0
name: fluke.algorithms.dpscaffold.DPSCAFFOLD
