data:
    client_split: 0.2
    dataset:
        name: medical
        path: ./data
    distribution:
        name: vertical_overlap
        feature_splits:
            - [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
            - [7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]
    keep_test: true
    sampling_perc: 1.0
    server_split: 0.0
    server_test: true
    uniform_test: false
eval:
    eval_every: 1
    locals: true
    post_fit: false
    pre_fit: false
    server: true
    task: classification
exp:
    device: cpu
    seed: 42
    inmemory: true
logger:
    name: CsvLog
    log_dir: runs/medical-vfl-vertical-overlap
protocol:
    eligible_perc: 1.0
    n_clients: 2
    n_rounds: 20
